### PR TITLE
Feature/edit profile

### PR DESCRIPTION
**Pull request by Manan-Sharma-5**
Screenshot 2024-08-09 at 5 20 42 PM

## Summary by CodeRabbit

- **New Features**
	- Introduced a `MemberPage` component for managing members, including add, edit, delete, and search functionalities.
	- Added a profile editing modal with enhanced input handling and validation.
	- Updated the sidebar menu to include a "Members" navigation option.
	- Implemented a validation schema for member data to enhance data integrity.

- **Bug Fixes**
	- Improved toast notification handling in the campaign creation process.

- **Style**
	- Added new styles for members management and profile editing interfaces.

- **Chores**
	- Refactored import statements and standardized code formatting. 
	- Updated project dependencies for enhanced functionality and compatibility.

### CODE REVIEW

**Comment by Manan-Sharma-5** [comment]
[Two instances of open ai on the sidebar](https://trello.com/c/WYws0bs9/18-two-instances-of-open-ai-on-the-sidebar)

**Comment by Manan-Sharma-5** [comment]
[react-native-image-picker should be replaced with expo-image-picker](https://trello.com/c/j5Vjh0P8/16-react-native-image-picker-should-be-replaced-with-expo-image-picker)

**Comment by Manan-Sharma-5** [comment]
[renderStep functions should be in names CompaignStep1](https://trello.com/c/gEnOqbMJ/15-renderstep-functions-should-be-in-names-compaignstep1)

**Comment by Manan-Sharma-5** [comment]
[User Profile Popup](https://trello.com/c/TMmK0w6h/18-user-profile-popup)

**Review by rahul-sinha1908 — APPROVED** [review]

**Review by rahul-sinha1908 — APPROVED** [review]

**Pull request merged**
