### PR TITLE
Bug fix/edit campaign

### PR DESCRIPTION
**Pull request by Manan-Sharma-5**
## Summary by CodeRabbit

- **New Features**
  - Introduced a new screen for editing campaigns, enhancing navigation.
  - Added functionality to create and edit campaigns with pre-filled data.
  - Implemented a new component for editing existing campaigns, fetching relevant data.

- **Bug Fixes**
  - Removed the `username` field from member data structures, improving data consistency.

- **Documentation**
  - Updated type definitions for campaign and lead stage interfaces to improve clarity and maintainability.

- **Chores**
  - Streamlined the data structure by removing unnecessary properties from schemas and contexts.

### CODE REVIEW

**Comment by Manan-Sharma-5** [comment]
[Edit feature for campaign missing. Open the same create campaign modal to edit.](https://trello.com/c/JDRtXRAC/56-edit-feature-for-campaign-missing-open-the-same-create-campaign-modal-to-edit)

**Comment by Manan-Sharma-5** [comment]
[Members - Added a new user but I dint get any mail](https://trello.com/c/jhdwN9BK/68-members-added-a-new-user-but-i-dint-get-any-mail)

**Comment by Manan-Sharma-5** [comment]
[After Login and onboard - Collaboration should be the default screen to open](https://trello.com/c/vZDb046y/74-after-login-and-onboard-collaboration-should-be-the-default-screen-to-open)

**Comment by Manan-Sharma-5** [comment]
[Cards should be clickable - Open View mode (Collaboration Details page)](https://trello.com/c/r11m0Wgx/76-cards-should-be-clickable-open-view-mode-collaboration-details-page)

**Comment by Manan-Sharma-5** [comment]
[Collaboration Search Bar - Margin is bit more. Also decrease height of the search bar abit](https://trello.com/c/eqNDDGih/78-collaboration-search-bar-margin-is-bit-more-also-decrease-height-of-the-search-bar-abit)

**Review by dev-rathore — APPROVED** [review]

**Pull request merged**
