### PR TITLE
Made bug fixes

### PR DESCRIPTION
**Pull request by Manan-Sharma-5**
## Summary by CodeRabbit

- **New Features**
	- Introduced a customizable header component for improved navigation across different screen sizes.
	- Enhanced layout structure of the campaign form with better input handling and validation.

- **Improvements**
	- Enabled member search functionality to enhance user experience.
	- Updated "Actions" column in the DataTable for better semantic structure.
	- Added consistent styling adjustments, including spacing and responsive design updates across various components.

- **Bug Fixes**
	- Improved data integrity with numeric validation for campaign input fields.

### CODE REVIEW

**Comment by Manan-Sharma-5** [comment]
[Create Campaign - Some feedbacks in the screenshot](https://trello.com/c/0DPzvcbJ/47-create-campaign-some-feedbacks-in-the-screenshot)

**Comment by Manan-Sharma-5** [comment]
[Open AI - Have consistent header. Refer Members Page](https://trello.com/c/w4Z8Fnrf/43-open-ai-have-consistent-header-refer-members-page)

**Comment by Manan-Sharma-5** [comment]
[Members - Move actions column to the very end](https://trello.com/c/dc5Mn5rB/48-members-move-actions-column-to-the-very-end)

**Comment by Manan-Sharma-5** [comment]
[Sign up page is not opening](https://trello.com/c/ZMyW5Aks/45-sign-up-page-is-not-opening)

**Review by rahul-sinha1908 — APPROVED** [review]

**Pull request merged**
