### PR TITLE
bug fixes and pr review fixes

### PR DESCRIPTION
**Pull request by Manan-Sharma-5**
## Summary by CodeRabbit

- **New Features**
	- Introduced a `GoBackButton` component for easier navigation.
	- Enhanced the `CreateCampaign` component with improved navigation handling.

- **Improvements**
	- Refactored the layout of navigation buttons for better alignment.
	- Updated styling for various input fields and components, enhancing visual consistency and responsiveness.

- **Bug Fixes**
	- Adjusted the `currentStep` logic in campaign creation components for accurate navigation.

- **Documentation**
	- Improved code formatting and consistency throughout the components.

### CODE REVIEW

**Comment by Manan-Sharma-5** [comment]
[Feedbacks for Create Campaign page](https://trello.com/c/9KYEae7X/35-feedbacks-for-create-campaign-page)

**Comment by Manan-Sharma-5** [comment]
[Feedback on Create Campaign Modal](https://trello.com/c/tt7GNijP/25-feedback-on-create-campaign-modal)

**Comment by Manan-Sharma-5** [comment]
[Use react-native-paper to make this design look better](https://trello.com/c/zlVsTJpS/28-use-react-native-paper-to-make-this-design-look-better)

**Comment by Manan-Sharma-5** [comment]
[Look into comments from the PR - 27](https://trello.com/c/mSTfsFWR/36-look-into-comments-from-the-pr-27)

**Review by rahul-sinha1908 — APPROVED** [review]

**Pull request merged**
