### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by Manan-Sharma-5**
## Summary by CodeRabbit

- **New Features**
	- Added an email property to the member data structure, allowing display of email addresses in the member management interface.
	- Enhanced user permission validation by modifying the "Delete" button logic to prevent users from deleting their own accounts.
	- Introduced a mechanism in the ProfilePopup to refresh user data after actions like image uploads.

- **Bug Fixes**
	- Improved responsiveness of user data management in the ProfileIcon and ProfilePopup components through context integration.

- **Chores**
	- Removed unnecessary console logs from the Sources component to enhance code readability.
	- Eliminated the fetchUser function call in the DrawerLayout component to streamline user data handling.

### CODE REVIEW

**Comment by Manan-Sharma-5** [comment]
[Profile image is not reflecting on the Edit Profile page](https://trello.com/c/xVmjeIGc/60-profile-image-is-not-reflecting-on-the-edit-profile-page)

**Comment by Manan-Sharma-5** [comment]
[Members -> You should not show delete button,  for your own user. Delete button should only show next to someone else's profile](https://trello.com/c/dddkmpFc/66-members-you-should-not-show-delete-button-for-your-own-user-delete-button-should-only-show-next-to-someone-elses-profile)

**Comment by Manan-Sharma-5** [comment]
[Members -> Show email, instead of username](https://trello.com/c/uQTS2WRz/64-members-show-email-instead-of-username)

**Comment by Manan-Sharma-5** [comment]
[Members -> Wherever there is a neccessity to put username, just use the email values in the username too](https://trello.com/c/yX8CyUng/65-members-wherever-there-is-a-neccessity-to-put-username-just-use-the-email-values-in-the-username-too)

**Comment by Manan-Sharma-5** [comment]
[After I edit the profile and add image, I need to refresh the page for image to reflect in the profile logo](https://trello.com/c/2OtASEOu/61-after-i-edit-the-profile-and-add-image-i-need-to-refresh-the-page-for-image-to-reflect-in-the-profile-logo)

**Review by dev-rathore — APPROVED** [review]

**Pull request merged**
